name: mt_weight
description: "A new Flutter package project."
version: 0.0.3

environment:
  sdk: ^3.0.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  mockito:
  build_runner:
